config/routes.rb
Rails.application.routes.draw do
  # get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :material_logs
  resources :materials do
    post 'add', on: :collection
    post 'remove', on: :collection
  end

  get '/users', to: redirect('/')
  root to: "home#index"

end

app/models/material.rb
class Material < ApplicationRecord
  before_create :set_was_manual_updated
  after_initialize :set_defaults, unless: :persisted?
  validates :name, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }


  def add_quantity(amount, user)
    return 'isnt_working_day' unless within_business_hours?
    if update(quantity: quantity + amount, was_manual_updated: true)
      log('add', amount, user)
      true
    else
      false
    end
  end

  def remove_quantity(amount, user)
    return 'isnt_working_day' unless within_business_hours?
    return false unless quantity >= amount
    if quantity >= amount && update(quantity: quantity - amount, was_manual_updated: true)
      log('remove', amount, user)
      true
    else
      false
    end
  end

  private

  def set_was_manual_updated
    self.was_manual_updated = false
  end

  def log(action, amount, user)
    new_log = MaterialLog.new({
        user_id: user.id,
        material_id: self.id,
        amount: amount,
        action: action,
      })
    new_log.save
  end

  def within_business_hours?
    current_time = Time.zone.now
    is_weekday = (1..5).cover?(current_time.wday)
    is_business_hours = (current_time.hour >= 9 && current_time.hour < 18)

    is_weekday && is_business_hours
  end

  def set_defaults
    self.quantity ||= 0
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_material, only: %i[ show edit update destroy add remove]

  # GET /materials or /materials.json
  def index
    @materials = if params[:search]
                   Material.order(:name).where('name ILIKE ?', "%#{params[:search]}%").page(params[:page]).per(10)
                 else
                   Material.order(:name).page(params[:page]).per(10)
                 end
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = Material.new(material_params)
    begin
      @material.save
    rescue ActiveRecord::RecordNotUnique => e
      @material.errors.add(:nome, "já esta sendo utilizado")
    end

    respond_to do |format|
      if @material.errors.blank?
        format.html { redirect_to material_url(@material), notice: "Material was successfully created." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to material_url(@material), notice: "Material was successfully updated." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add
    response = @material.add_quantity(params[:add_quantity].to_i, current_user)
    if response.eql?(true)
      redirect_to materials_url, notice: "Material quantity was successfully added."
    elsif response.eql?('isnt_working_day')
      redirect_to materials_url, alert: "No update permitted out of work day range."
    else
      redirect_to materials_url, alert: "Failed to add material quantity."
    end
  end

    def remove
    response = @material.remove_quantity(params[:remove_quantity].to_i, current_user)
    if response.eql?(true)
      redirect_to materials_url, notice: "Material quantity was successfully removed."
    elsif response.eql?('isnt_working_day')
      redirect_to materials_url, alert: "No update permitted out of work day range."
    else
      redirect_to materials_url, alert: "Failed to remove material quantity."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_material
    @material = Material.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def material_params
    params.require(:material).permit(:name, :quantity)
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <% if local_assigns[:show_quantity] %>
    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, required: true %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title">Editing Material</h1>
          <%= render 'form', material: @material, show_quantity: false %>
        </div>
        <div class="card-footer text-muted">
          <%= link_to 'Show', @material, class: 'btn btn-info me-2' %>
          <%= link_to 'Back', materials_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/materials/index.html.erb
<h1>Materials</h1>
<%= form_tag materials_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
<br>
<%= link_to 'New Material', new_material_path, class: 'btn btn-success' %>
<%= link_to 'Logs', material_logs_path, class: 'btn btn-secondary' %>
<br><br>
<table class="table col-lg-10 offset-lg-1">
  <thead>
    <tr class='table-info'>
      <th>#</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Edit</th>
      <th>Delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each_with_index do |material, i| %>
      <% row_class = i.odd? ? 'table-primary' : 'table-secondary' %>
      <tr class="<%= row_class %>" %>
        <td><%= i + 1 %></td>
        <td><%= material.name %></td>
        <td><%= material.quantity %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td>
          <% unless material.was_manual_updated %>
            <%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Deseja mesmo deletar esse material?' } %>
          <% end %>
        </td>

        <!-- Adicionar Materiais -->
        <td>
          <%= form_with url: add_materials_path(id: material.id), method: :post, local: true do |form| %>
            <%= form.number_field :add_quantity, step: 1, min: 1, class: 'input-number-field', size: 10, required: true %>
            <%= form.submit "Add material", class: "small-button" %>
          <% end %>
        </td>

        <!-- Sacar Materiais -->
        <td>
          <%= form_with url: remove_materials_path(id: material.id), method: :post, local: true do |form| %>
            <%= form.number_field :remove_quantity, in: 1..material.quantity, step: 1, min: 1, class: 'input-number-field', size: 10, required: true %>
            <%= form.submit "Remove material", class: "small-button" %>
          <% end %>
        </td>
        <style media="screen">
          .input-number-field {
            width: 100px;
          }
        </style>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @materials %>

app/views/materials/new.html.erb
<div class="container mt-4">
  <h1 class="mb-4">New Material</h1>

  <% if @material.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Os seguintes erros impediram material de ser salvo:</h4>
      <ul>
        <% @material.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <%= render 'form', material: @material, show_quantity: true %>
    </div>
  </div>

  <div class="mt-3">
    <%= link_to 'Back', materials_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/materials/show.html.erb
<div class="container mt-4">
  <div class="card">
    <div class="card-header">
      Material Details
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @material.name %></h5>
      <p class="card-text">
        <strong>Quantity:</strong>
        <%= @material.quantity %>
      </p>
      <%= link_to 'Edit', edit_material_path(@material), class: 'btn btn-primary me-2' %>
      <%= link_to 'Back', materials_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>